jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', '3.x']
    name: Test ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        run: |
         pip install pytest pytest-coverage codecov
         pip install -e ./
      - name: Run tests
        run: pytest -v tests.py --cov magicattr --cov-report xml
      - name: Run codecov
        run: codecov
